apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  namespace: homework
  labels: {
    app: homework
    }
spec:
  containers:
  - name: wordpress
    image: wordpress
    ports:
    - containerPort: 8080
