apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  namespace: homework
  labels:
    app: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 8080
